import type { ImpactEvent, CivicIQ, UserAddress, CadProperty } from './types'

export const mockProperty: CadProperty = {
  id: 'collin-2862701',
  county: 'collin',
  year: 2025,
  address: '1201 PARKSIDE PL, CELINA, TX 75009',
  street_number: '1201',
  street_name: 'PARKSIDE',
  street_suffix: 'PL',
  city: 'CELINA',
  zip: '75009',
  assessed_value: 487_500,
  market_value: 565_000,
  land_value: 95_000,
  improvement_value: 392_500,
  prev_assessed_value: 455_000,
  school_district_code: 'SCE',
  city_code: 'CCE',
  mud_code: 'MUD23',
  entity_codes: ['GCN', 'JCN', 'SCE', 'CCE', 'MUD23'],
  homestead_exempt: true,
  exemption_codes: ['HS'],
  prop_type: 'Real',
  prop_subtype: 'Residential',
  year_built: 2021,
  owner_name: 'HOMEOWNER',
  is_owner_occupied: true,
}

export const mockUserAddress: UserAddress = {
  id: 'ua-001',
  user_id: 'user-001',
  cad_property_id: 'collin-2862701',
  county: 'collin',
  address: '1201 Parkside Pl, Celina, TX 75009',
  zip: '75009',
  assessed_value: 487_500,
  school_district_code: 'SCE',
  city_code: 'CCE',
  mud_code: 'MUD23',
  homestead_exempt: true,
  is_primary: true,
  created_at: '2026-01-15T00:00:00Z',
}

export const mockImpactEvents: ImpactEvent[] = [
  {
    id: 'evt-001',
    county: 'collin',
    source: 'legistar',
    meeting_date: '2026-03-18',
    meeting_type: 'Collin County Commissioners Court',
    agenda_item_id: 'CC-2026-0318-07',
    title: 'FY 2026 Tax Rate Adoption',
    summary: 'Collin County adopts a proposed tax rate of 0.1534 per $100 assessed value • Up from 0.1520 — a $68 annual increase on a $487,500 home • Public comment period open through April 5',
    impact_type: 'tax_rate_change',
    rate_change_pct: 0.000014,
    avg_dollar_impact: 68,
    source_pdf_url: 'https://legistar.com/collin/pdf/2026-0318-taxrate.pdf',
    source_pdf_page: 4,
    confidence: 'high',
    civic_iq_delta: 6.8,
    created_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'evt-002',
    county: 'collin',
    source: 'legistar',
    meeting_date: '2026-02-24',
    meeting_type: 'Celina City Council',
    agenda_item_id: 'CC-2026-0224-03',
    title: 'Celina Ranch PD Rezoning — 240 Acres',
    summary: 'City Council considers rezoning 240 acres east of Celina Ranch from agricultural to mixed residential (R-2/R-3) • Up to 680 new homes would add pressure to Celina ISD enrollment • Traffic study required before final approval',
    impact_type: 'zoning_change',
    source_pdf_url: 'https://legistar.com/celina/pdf/2026-0224-rezoning.pdf',
    source_pdf_page: 2,
    confidence: 'high',
    civic_iq_delta: 3.2,
    created_at: '2026-02-24T19:00:00Z',
  },
  {
    id: 'evt-003',
    county: 'collin',
    source: 'legistar',
    meeting_date: '2026-01-14',
    meeting_type: 'Celina ISD Board of Trustees',
    agenda_item_id: 'CISD-2026-0114-05',
    title: '$480M Bond Election — May 2026',
    summary: 'Celina ISD board approves placing a $480M bond on the May ballot for 3 new elementary schools and a second high school • If approved, estimated 4.2-cent tax rate increase per $100 assessed value • For a $487,500 home with homestead exemption, adds roughly $166/year',
    impact_type: 'bond_election',
    rate_change_pct: 0.000042,
    avg_dollar_impact: 166,
    source_pdf_url: 'https://legistar.com/celina/pdf/2026-0114-bond.pdf',
    source_pdf_page: 7,
    confidence: 'high',
    civic_iq_delta: 9.1,
    created_at: '2026-01-14T18:30:00Z',
  },
  {
    id: 'evt-004',
    county: 'collin',
    source: 'legistar',
    meeting_date: '2025-11-12',
    meeting_type: 'McKinney City Council',
    agenda_item_id: 'MC-2025-1112-11',
    title: 'US-380 Widening — SH 5 to Lake Forest',
    summary: 'TxDOT and McKinney approve final design for 380 corridor widening • Construction starts Q3 2026, expect 18-month lane closures • No direct tax impact — funded by state and federal grants',
    impact_type: 'infrastructure',
    source_pdf_url: 'https://legistar.com/mckinney/pdf/2025-1112-380.pdf',
    source_pdf_page: 1,
    confidence: 'estimated',
    civic_iq_delta: 1.5,
    created_at: '2025-11-12T20:00:00Z',
  },
  {
    id: 'evt-005',
    county: 'collin',
    source: 'legistar',
    meeting_date: '2025-09-09',
    meeting_type: 'Collin County Commissioners Court',
    agenda_item_id: 'CC-2025-0909-06',
    title: 'FY 2025 Budget — $1.2B Approval',
    summary: 'Commissioners approve $1.2B operating budget, maintaining the 0.1520 per $100 tax rate • No tax rate increase for residents this fiscal year • Largest budget in county history — driven by 14% population growth',
    impact_type: 'budget_approval',
    source_pdf_url: 'https://legistar.com/collin/pdf/2025-0909-budget.pdf',
    source_pdf_page: 3,
    confidence: 'high',
    civic_iq_delta: 2.0,
    created_at: '2025-09-09T14:00:00Z',
  },
]

export const mockCivicIQ: CivicIQ = {
  user_address_id: 'ua-001',
  score: 73,
  tax_exposure_12m: 234,
  pending_impact: 166,
  zoning_risk: 'medium',
  school_district_trend: 'stable',
  calculated_at: '2026-04-21T00:00:00Z',
  events_included: 5,
}

// Dollar impact per event for the mock user's property
export const mockDollarImpacts: Record<string, number | null> = {
  'evt-001': 68,
  'evt-002': null,
  'evt-003': 166,
  'evt-004': null,
  'evt-005': 0,
}
